name: Build & Push Keycloak Plugin

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build plugin
        run: mvn clean package -DskipTests

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/dagabriel237/keycloak-kafka-plugin:latest \
            -t ghcr.io/dababriel237/keycloak-kafka-plugin:${{ github.sha }} \
            .

      - name: Push latest image
        run: docker push ghcr.io/dagabriel237/keycloak-kafka-plugin:latest

      - name: Push SHA image
        run: docker push ghcr.io/dagabriel237/keycloak-kafka-plugin:${{ github.sha }}
